services:
  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin:18.3.0
    command: server start
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - "./config:/config"
    ports:
      - 8888:8888
    env_file:
      - .env
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "true"
      ATUIN_DB_URI: sqlite:///config/atuin.db
      RUST_LOG: info,atuin_server=debug
